# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "kestrel-client-jruby"
  s.version = "0.7.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Freels", "Rael Dornfest"]
  s.date = "2012-03-28"
  s.description = "Ruby client for the Kestrel queue server"
  s.email = "rael@twitter.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "kestrel-client.gemspec",
    "lib/kestrel-client.rb",
    "lib/kestrel.rb",
    "lib/kestrel/client.rb",
    "lib/kestrel/client/blocking.rb",
    "lib/kestrel/client/envelope.rb",
    "lib/kestrel/client/json.rb",
    "lib/kestrel/client/namespace.rb",
    "lib/kestrel/client/partitioning.rb",
    "lib/kestrel/client/proxy.rb",
    "lib/kestrel/client/stats_helper.rb",
    "lib/kestrel/client/transactional.rb",
    "lib/kestrel/client/unmarshal.rb",
    "lib/kestrel/config.rb",
    "spec/kestrel/client/blocking_spec.rb",
    "spec/kestrel/client/envelope_spec.rb",
    "spec/kestrel/client/json_spec.rb",
    "spec/kestrel/client/namespace_spec.rb",
    "spec/kestrel/client/partitioning_spec.rb",
    "spec/kestrel/client/transactional_spec.rb",
    "spec/kestrel/client/unmarshal_spec.rb",
    "spec/kestrel/client_spec.rb",
    "spec/kestrel/config/kestrel.yml",
    "spec/kestrel/config_spec.rb",
    "spec/kestrel_benchmark.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/freels/kestrel-client"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "JRuby Kestrel client"

  if ENV['JAVA_GEM'] or defined?(::JRUBY_VERSION)
    s.platform = "java"
    s.add_runtime_dependency(%q<jruby-memcached>, [">= 0.5.5"]) 
    s.require_paths += %w[java]
  else
    s.platform = "ruby"
    s.add_runtime_dependency(%q<memcached>, [">= 1.8.0"]) 
  end
end

